### PR TITLE
Connect callback

### PR DESCRIPTION
**Pull request by moander**

### CODE REVIEW

**Comment by tvrprasad** [comment]
What's the purpose of this callback? Just curious.

**Comment by moander** [comment]
The Request class takes a callback in the constructor but the Connection does not.

**Comment by tvrprasad** [comment]
I looked at the Request and it doesn't seem like the callback is ever invoked.
I ran a test with some logging and I don't see if invoked.

I think that's dead code that needs to be removed.

**Comment by tvrprasad** [comment]
Closing the PR as the callback parameter added is unused.

**Pull request closed without merging**
