### PR TITLE
fix #1018

### LINKED ISSUE #1018: DateTime parameter,the Day is wrong when time >'23:59:16'
[https://github.com/tediousjs/node-mssql/issues/962#issue-540075836](url)

### PR DESCRIPTION
**Pull request by mrliuc**
**Before submitting a PR :**
1. Ensure your fork is created from `master` branch of [the repository](https://github.com/tediousjs/tedious).
2. Run `npm install` in the root folder.
3. After bug fix/code change, ensure all the existing tests and new tests (if any) pass (`npm run-script test-all`). During development, to run individual test use `node_modules/nodeunit test/<test_file.js> -t <test_name>`.
4. Build the driver (`npm run build`).
5. Run eslint and flow typechecker (`npm run lint`).
6. Run commitlint (`node_modules/.bin/commitlint --from origin/master --to HEAD`). Refer [commit conventions](https://commitlint.js.org/#/concepts-commit-conventions) and [commit rules](https://commitlint.js.org/#/reference-rules).

**Thank you for Contributing!**

### CODE REVIEW

**Comment by arthurschreiber** [comment]
Oh, this is great, thanks! ❤️ I'll review, merge and release this over the next few days.

**Comment by dhensby** [comment]
@arthurschreiber - I'm not familiar with UTC dates in JS so I don't know if this is the right fix, but this seems to be caused by a problem with timezones (possibly?)

The node-mssql lib's test suite has a test for this already that fails locally on my mac unless I provide the `TZ=UTC` env var. Is there a more elegant way of correcting this than checking if ms is >= `86357000` which seems like hard coding a value that just happens to be there without truly understanding what's going on and why?

Won't think have implications for any date where the time is `>= 23:59:17` ? I'd like to see a test to make sure it doesn't start removing days from dates just because the time is late

see https://github.com/tediousjs/node-mssql/issues/962#issuecomment-568189352

**Comment by mrliuc** [comment]
I did some tests and found this value 86357000 ，but this solution is really temporary 。

I am looking forward to the official solution...

**Comment by dhensby** [comment]
> I did some tests and found this value 86357000 ，but this solution is really temporary 。

did you look into whether there are any timezone discrepancies?

**Comment by arthurschreiber** [comment]
@dhensby I'm not sure if that's relevant here, but timezone support is basically non-existant in `Date` objects. The support is basically limited to parsing strings with a timezone identifier, but the resulting `Date` object won't carry the timezone information with it, and will have the timezone of the node process instead, I think. And then any calculations that are made on that object will be made in the process' timezone, so things like DST changes will probably end up incorrect.

I'm not sure if that's the issue here. I'll read up on the discussion over in https://github.com/tediousjs/node-mssql/issues/962#issuecomment-568189352 and try to understand what this code is supposed to fix and get back to this PR soon. 🙇

**Comment by arthurschreiber** [comment]
@mrliuc Which timezone is your SQL Server and your Node.js app running in? I can't reproduce this at all. 🤔

**Comment by mrliuc** [comment]
> @mrliuc Which timezone is your SQL Server and your Node.js app running in? I can't reproduce this at all. 🤔

The timezone is (UTC+08:00),and the configuration set `"useUTC": false

**Comment by mrliuc** [comment]
I think I fixed the issue this time,

The time part  is always right, just the day is wrong,so I thought was there any problem with the day algorithm ?

[fix #1018](https://github.com/tediousjs/tedious/pull/1019/commits/ac48d86c996abff6fd57ec100fff1b8903fdfce3)

**Pull request closed without merging**
