### PR TITLE
remove last bits of coffee-script

### PR DESCRIPTION
**Pull request by rossipedia**
This ended up being a bit easier than I thought, thanks to [decaffeinate](http://decaffeinate-project.org/). There are still probably a _ton_ of superfluous return statements, but the test results are the same as the coffee-script versions. Can drop the [arthur/drop-coffee-script](https://github.com/tediousjs/tedious/tree/arthur/drop-coffee-script) branch as well when this gets merged.

(spiritual successor to #463)

### CODE REVIEW

**Comment by rossipedia** [comment]
Hmmmm, seems unlikely that the node 4 and 7 version would pass, but 6 wouldn't.

**Comment by rossipedia** [comment]
Wait... it seems as though this isn't the latest Travis build, [this one is](https://travis-ci.org/tediousjs/tedious/builds/231372077) and it passed. So all good?

**Comment by rossipedia** [comment]
if this checks out I'll rebase onto `master` and push as a smaller changeset

**Comment by tvrprasad** [comment]
@rossipedia I'll review and help get this in once you have the final version pushed. Thanks for your efforts.

**Comment by rossipedia** [comment]
@tvrprasad thanks! I'm bisecting now to figure out where the tests are failing

**Comment by rossipedia** [comment]
ok tests are passing, going to rebase and open as another PR

**Pull request closed without merging**
