### PR TITLE
Move to Mocha

### PR DESCRIPTION
**Pull request by arthurschreiber**
As promised a long time ago, I started to work on converting all of Mochas Unit and Integration tests from `nodeunit` over to `mocha`.

Here's what I have so far, but it's still pretty much WIP, but I think this nicely show cases the benefits of the move.

### CODE REVIEW

**Comment by arthurschreiber** [comment]
@bretcope Is there still interest in this?

**Comment by bretcope** [comment]
I think moving to mocha would be a good thing since it's more commonly used and understood by node developers. Whether or not it happens depends entirely on whether you want to do it. No one will complain about making the switch... but no one is likely to help either.

**Comment by Hadis-Fard** [comment]
@arthurschreiber what's the roadmap on this one? what are your thoughts about writing  new tests in Mocha for any new changes and converting the nodeunit tests in batches over the time? meanwhile we can run both in parallel, and when we have moved to Mocha completely we delete the nodeunit from CI.

**Comment by arthurschreiber** [comment]
Closing this in favor of #746.

**Pull request closed without merging**
