### PR TITLE
948 cancelling before buffering

### PR DESCRIPTION
**Pull request by IanChokS**
A fix for issue #948

### CODE REVIEW

**Comment by irgijs** [comment]
@IanChokS Do you know when this can be merged?

**Comment by arthurschreiber** [comment]
@IanChokS Do you think we can build a test case that shows this issue is fixed? 🤔

**Comment by IanChokS** [comment]
@arthurschreiber A test has been added! :)

**Comment by ErikJansenIRefact** [comment]
Is there any reason why this fix isn't released?

**Comment by IanChokS** [comment]
@ErikJansenIRefact, just waiting for @arthurschreiber's approval

**Comment by IanChokS** [comment]
moved to #1033

**Pull request closed without merging**
