### PR TITLE
Refactor: test/unit tests from nodeunit to mocha

### PR DESCRIPTION
**Pull request by IanChokS**
Refactor test/unit test files from nodeunit to mocha. Other files not in this PR has already been refactored to mocha from @MichaelSun90 in his PR #870.

### CODE REVIEW

**Comment by arthurschreiber** [comment]
@IanChokS Awesome work so far! 😍

According to https://travis-ci.org/tediousjs/tedious/jobs/565157784, there's a bunch of style related issues, but you should be able to fix them via eslint.

**Comment by IanChokS** [comment]
Resolved package.json conflicts

**Comment by IanChokS** [comment]
Should I remove the package-lock.json from this PR?

**Comment by arthurschreiber** [comment]
@IanChokS I pushed a few additional changes that cleaned up some smaller issues.

I see there's still a few nodeunit tests left. What's your plan for those?

**Comment by IanChokS** [comment]
Thanks for the help to clean up some stuff. I left a few old nodeunit tests because @MichaelSun90  has already converted those into mocha in his PR #870 such as connection-config-validation, data-type, etc...

**Comment by arthurschreiber** [comment]
@IanChokS I think it might make sense to merge his changes into this branch, and get everything cleaned up in one PR. What do you think? 🤔

**Comment by IanChokS** [comment]
Yeah that would make more sense. I'll work on merging his PR into this one.

**Comment by IanChokS** [comment]
@arthurschreiber  Ok I've merged Michael's PR #870 into this pr :)

**Comment by IanChokS** [comment]
Travis-CI is failing for sender-test.js test, but that is passing for me locally. Perhaps try re-running the build again? 
image

**Comment by arthurschreiber** [comment]
@IanChokS I did some cleanup of the history here, I hope that's ok. 🙇I also pulled out the code coverage related changes. I think adding code coverage is a good idea, but let's do that in a separate PR.

@IanChokS @MichaelSun90 Huge thanks to both of you for making this migration happen! 🙇 ❤️ 🙌

**Pull request merged**
