### PR TITLE
guidToArray performance tuning

### LINKED ISSUE #441: guidToArray performance tuning
@arthurschreiber this is the counterpart to https://github.com/tediousjs/tedious/pull/440

https://gist.run/?id=72ba5c3588d6375fee052fc8358a4606

I can send a PR if it looks good.

### PR DESCRIPTION
**Pull request by jdanyow**
fixes #441

### CODE REVIEW

**Comment by jdanyow** [comment]
@arthurschreiber ping

**Comment by arthurschreiber** [comment]
@jdanyow Can you change the test case to not be written in CoffeeScript? We want to move away from CoffeeScript long-term, and adding new files containing CoffeeScript will just make this harder in the future.

Other than that, these changes look great and I'm really looking forward on merging this! ❤️

**Comment by jdanyow** [comment]
Ha- sure. I actually had to learn coffeescript to write the tests.

**Comment by arthurschreiber** [comment]
@jdanyow Oh man, that sucks and I'm sorry about that. 😞

If I find some time I'll add some words regarding the state of CoffeeScript in tedious to the readme, so other people don't go through the same trouble as you did!

**Comment by jdanyow** [comment]
No worries

**Comment by jdanyow** [comment]
@arthurschreiber - the guid-parser tests have been converted to js.

**Comment by arthurschreiber** [comment]
Awesome! This is looking so great! ❤️

**Pull request merged**
