### PR TITLE
Add additional config options:

### PR DESCRIPTION
**Pull request by tvrprasad**
dateFormat, enableAnsiNull, enableAnsiPadding, enableAnsiWarnings,
enableConcatNullYeldsNull, enableCursorCloseOnCommit,
enableImplicitTransactions, enableNumericRoundabort, enableQuotedIdentifier,
language.

Relates to #507 #506 #501 #503

This is a cleaned up merged version of #508.

### CODE REVIEW

**Comment by tvrprasad** [comment]
This is a cleaned up version of https://github.com/tediousjs/tedious/pull/508. Had to do a manual merge because of the extensive changes that happened in the mean time.

**Comment by tvrprasad** [comment]
@arthurschreiber @rossipedia Can I get a code review? Can't commit without an approval anymore :-)

@ariskemper Please note that I attributed the original commit on this PR to you. Thanks for putting the original together. If you're able to make a pass that'll be great.

**Comment by ariskemper** [comment]
@arthurschreiber @rossipedia @tvrprasad will this be merged in next release?

**Comment by tvrprasad** [comment]
@ariskemper I'm waiting on a review to commit this.

**Comment by ariskemper** [comment]
I made quick review and it looks ok to me, however it needs rebase with master.

**Comment by tvrprasad** [comment]
@v-suhame This is another PR that's been lying around waiting for approval. I'll appreciate if you're able to take it through and merge. This should be a relatively straightforward merge. And there are folks very much interested in these new options.

**Comment by v-suhame** [comment]
done 👍

**Comment by tvrprasad** [comment]
Awesome :-)

**Pull request merged**
