### PR TITLE
chore: update semantic-release version

### PR DESCRIPTION
**Pull request by Hadis-Fard**
Version 6 installs deprecated packages, updated to fix warning messages on install

### CODE REVIEW

**Comment by arthurschreiber** [comment]
@Hadis-Fard Thank you so much! 😍 

Could you bump this to the latest `semantic-release` version? Right now, this would be `12.2.2`.

Also, there have been a few breaking changes between the version of `semantic-release` we're currently using and the latest version released. From going through their changelog, it looks like we'll also need to change this line https://github.com/tediousjs/tedious/blob/f5a0f95a5a522ad6a312170201b829e70c866976/package.json#L74 to
```
"semantic-release": "semantic-release"
```

We'll also be able to update our travis configuration on this line https://github.com/tediousjs/tedious/blob/f5a0f95a5a522ad6a312170201b829e70c866976/.travis.yml#L62 to
```
script: npm run semantic-release
```

Could you include these changes in this pull request, as merging this pull request without these changes will break the semantic-release configuration. 😅

**Comment by arthurschreiber** [comment]
Also, I think this will require upgrading the `release` stage configuration in the travis config to run with node v8 instead of v4. 😅

**Comment by Hadis-Fard** [comment]
aaa thanks for checking the release notes, done and done 😸

**Comment by arthurschreiber** [comment]
Sweet! 😍 I'll try to get this merged this weekend.

**Comment by arthurschreiber** [comment]
Thank you @Hadis-Fard! I squashed the changes together before merging.

**Pull request merged**
