### PR TITLE
fix: add Node.js v20 support by bumping `@azure/identity` to `v3.4.1`

### PR DESCRIPTION
**Pull request by esetnik**
**Before submitting a PR :**
1. Ensure your fork is created from `master` branch of [the repository](https://github.com/tediousjs/tedious).
2. Run `npm install` in the root folder.
3. After bug fix/code change, ensure all the existing tests and new tests (if any) pass (`npm run-script test-all`). During development, to run individual test use `node_modules/nodeunit test/<test_file.js> -t <test_name>`.
4. Build the driver (`npm run build`).
5. Run eslint and flow typechecker (`npm run lint`).
6. Run commitlint (`node_modules/.bin/commitlint --from origin/master --to HEAD`). Refer [commit conventions](https://commitlint.js.org/#/concepts-commit-conventions) and [commit rules](https://commitlint.js.org/#/reference-rules).

**Thank you for Contributing!**

### CODE REVIEW

**Comment by esetnik** [comment]
Looks like only v2 of `azure/msal-node` will support node 20
 https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6167

**Comment by MichaelSun90** [comment]
Thanks for make this change. we will double check see if the latest 3.0 version and NodeJS 20 has any compatibility issue with the current setup, then merge it if everything looks good.

**Comment by esetnik** [comment]
> Thanks for make this change. we will double check see if the latest 3.0 version and NodeJS 20 has any compatibility issue with the current setup, then merge it if everything looks good.

It looks like `@azure/identity` only supports node LTS which won't become v20 until 10/26/2023, however I wanted to add node 20 to the compatibility matrix now so that we can ensure `tedious` doesn't have any issues.

Release | Status | Codename | Initial Release | Active LTS Start | Maintenance LTS Start | End Of Life
-- | -- | -- | -- | -- | -- | --
V20 | Current |   | 2023-04-18 | 2023-10-24 | 2024-10-22 | 2026-04-30
V18 | Active LTS | Hydrogen | 2022-04-19 | 2022-10-25 | 2023-10-18 | 2025-04-30
V16 | Maintenance LTS | Gallium | 2021-04-20 | 2021-10-26 | 2022-10-18 | 2023-09-11

Release	Status	Codename	Initial Release	Active LTS Start	Maintenance LTS Start	End Of Life
[V20](https://nodejs.org/download/release/latest-v20.x/)	Current		2023-04-18	2023-10-24	2024-10-22	2026-04-30
[V18](https://nodejs.org/download/release/latest-v18.x/)	Active LTS	[Hydrogen](https://nodejs.org/download/release/latest-hydrogen/)	2022-04-19	2022-10-25	2023-10-18	2025-04-30
[V16](https://nodejs.org/download/release/latest-v16.x/)	Maintenance LTS	[Gallium](https://nodejs.org/download/release/latest-gallium/)	2021-04-20	2021-10-26	2022-10-18	2023-09-11

**Comment by esetnik** [comment]
Hi @MichaelSun90 now that node 20 is LTS can we get another look at this?

**Comment by absci** [comment]
> Hi @MichaelSun90 now that node 20 is LTS can we get another look at this?

Hi, Michael is on vacation currently, we'll look into supporting this in the future.

**Comment by semics-tech** [comment]
@esetnik @MichaelSun90 probably worth merging in with @azure/identity v4.0.0 as they have just implemented node 20 support.

https://github.com/Azure/azure-sdk-for-js/issues/26886#issuecomment-1793132348

**Comment by esetnik** [comment]
> @esetnik @MichaelSun90 probably worth merging in with @azure/identity v4.0.0 as they have just implemented node 20 support.
> 
> [Azure/azure-sdk-for-js#26886 (comment)](https://github.com/Azure/azure-sdk-for-js/issues/26886#issuecomment-1793132348)

Looks like this would also necessitate dropping node 16 support from tedious if I'm reading the above comments correctly...

**Comment by arthurschreiber** [comment]
Do you mind updating this PR to version `3.4.1` of `@azure/identity`?

**Comment by esetnik** [comment]
> Do you mind updating this PR to version `3.4.1` of `@azure/identity`?

Just pushed the update

**Comment by mmachatschek** [comment]
@arthurschreiber it seems like 16.6.1 wasn't pushed as the `latest` tag to npm 🤔 

image

**Comment by arthurschreiber** [comment]
That's how new releases of `tedious` are managed. When a new version is released, the `latest` tag is only updated a week or so later.

**Pull request merged**
