### PR TITLE
fix: support properly TIME(x) when x<5

### PR DESCRIPTION
**Pull request by kalinkrustev**

### CODE REVIEW

**Comment by arthurschreiber** [comment]
@kalinkrustev Oh wow, that is a pretty neat fix! Do you think you could also add some test cases for this? If not, that's okay too! ❤️

**Comment by kalinkrustev** [comment]
I did manual tests and it resolved my issues. I can check about test cases tomorrow.

**Comment by arthurschreiber** [comment]
> I can check about test cases tomorrow.

Cool, thanks! Once you pushed a test case, I'll merge this and it'll trigger a new release. ❤️

**Comment by kalinkrustev** [comment]
Added some integration tests, that ensure time is stored with the intended precision.

**Pull request merged**
