### PR TITLE
fix unhandled error after timeout when connecting with ip

### PR DESCRIPTION
**Pull request by Hadis-Fard**
passing the socket to the connection and checking the final state in the socket error fixed the issue #782

### CODE REVIEW

**Comment by kuseni** [comment]
@Hadis-Fard , yes, socket is created in initialiseConnection at 21:56:46 (in my last comment in #782),  but connection timeout emmits connect event (with err != null) at 21:57:01. Socket is created already at 21:57:01, but it's local for Connector yet and is not visible for Connection (so connectTimeout can't destroy it). Socket's error event is emmited at 21:57:07, so Node can't exit at 21:57:01 (immediately after connection timeout) because there is a non-destroyed socket and waits 6 seconds more to exit. I think it's more correctly to destroy socket on connection timeout and don't wait 6 seconds more (I'm not good in tedious architecture and Connection states, so I can't propose a solution - publishing socket to Connection immediately on creation OR providing Connector.cancel() method OR something else - but I am convicted that Node should exit immediately after connection timeout, not 6 seconds later)

**Comment by kuseni** [comment]
I think it's possible to destroy socket in connecting state:
```javascript
const util = require('util');
const net = require('net');

function log(...args) {
	var dt = new Date();
	dt.setMinutes(dt.getMinutes() - dt.getTimezoneOffset());
	process.stdout.write(`${dt.toISOString().slice(0, -1).replace('T', ' ')}: ${util.format.apply(null, args).replace(/\n/g, '\n  ')}\n`);
}

log('started');

const socket = net.connect({ host: '8.8.8.8', port: 1433});
socket.on('error', (err) => log(`${err}`));
setTimeout(() => {
	log(`timeout, socket.connecting = ${socket.connecting}`);
	socket.destroy();
}, 15000);
process.on('exit', () => log('exit'));
```

```
2018-10-17 13:09:57.607: started
2018-10-17 13:10:12.615: timeout, socket.connecting = true
2018-10-17 13:10:12.619: exit
```

**Comment by arthurschreiber** [comment]
I think a better fix would be to push down the timeout handling into the `Connector` class, and remove it from `Connection`.

**Comment by Suraiya-Hameed** [comment]
🤔 we would still need part of timeout handling in `Connection`, as `Connector` class only handles socket and we need connection timeout to consider entire login process.

**Comment by arthurschreiber** [comment]
I'm closing this, as the underlying issue was properly fixed via https://github.com/tediousjs/tedious/pull/1210.

**Pull request closed without merging**
