### PR TITLE
#718

### PR DESCRIPTION
**Pull request by SteveyPugs**
Adds support in the readme for 2016 and 2017

### CODE REVIEW

**Comment by Hadis-Fard** [comment]
Thanks @SteveyPugs

**Comment by v-suhame** [comment]
@SteveyPugs Can you also update [index page]( https://github.com/tediousjs/tedious/blob/gh-pages/index.html#L28)?

**Comment by SteveyPugs** [comment]
@v-suhame this is done though I am not sure I have done it right. I never did two pull requests across multiple branches.

https://github.com/tediousjs/tedious/pull/721

**Comment by v-suhame** [comment]
@SteveyPugs Thanks :) Can you update this PR with changes from #721 and close the other one? 😅 
You can add new changes to your `SteveyPugs-master` branch, commit and push it. That will automatically update this PR.

**Comment by SteveyPugs** [comment]
@v-suhame I don't follow. They are two different branches. You want me to make the index.html page to the master branch?

**Comment by SteveyPugs** [comment]
@v-suhame I apologize as I have never done that concept. If you could walk me through it that would be great.

**Comment by v-suhame** [comment]
Got it! Sorry, forgot they were in 2 different branches. You are right, separate PR is the way to go.

**Comment by SteveyPugs** [comment]
Oh, good. I thought I was losing my mind. So will this be approved?

**Comment by v-suhame** [comment]
@SteveyPugs Your PR is already approved :) Can you fix the commit message so CI can pass? It should follow the convention in [commitlint](https://github.com/marionebl/commitlint/tree/master/%40commitlint/config-conventional).

**Comment by SteveyPugs** [comment]
So like this correct?

**fix: adds support for 2016/2017 mssql**

**Comment by SteveyPugs** [comment]
@v-suhame all set on both pull requests. #719 and #721.

Thanks again!

**Comment by SteveyPugs** [comment]
We good here?

**Comment by SteveyPugs** [comment]
@v-suhame are we waiting on anything else?

**Comment by v-suhame** [comment]
@SteveyPugs Thanks for contributing :)

**Pull request merged**
