### PR TITLE
fix: improve `UniqueIdentifier` data type validation

### PR DESCRIPTION
**Pull request by arthurschreiber**
Fixes: https://github.com/tediousjs/tedious/issues/1085
Closes: https://github.com/tediousjs/tedious/pull/1086

---

@dhensby Can you take a look? 🙇‍♂️

### CODE REVIEW

**Comment by dhensby** [comment]
This looks like it would solve the specific problem that is being reported regarding GUIDs, but not the more generic issue of errors being thrown in the stream, which my original patch tried to handle.

**Comment by arthurschreiber** [comment]
> This looks like it would solve the specific problem that is being reported regarding GUIDs, but not the more generic issue of errors being thrown in the stream, which my original patch tried to handle.

@dhensby I think I mentioned this before, but the patch you provided would've left the connection in an undefined state. I'll see what I can do about better error handling, but I think the proper approach is to actually fix the code so that no errors happen in the first place.

**Comment by arthurschreiber** [comment]
@dhensby Would you like to see this PR to be backported to some older versions? 🙇‍♂️

**Comment by dhensby** [comment]
Thanks @arthurschreiber! In terms of backporting, mssql is still using v6 and our v7 alpha is using v8 (but that could be bumped to v9 before release).

I doubt you really want to back port this to v6, but it would allow us to tick this off as fixed in our current stable version. Otherwise I'll just direct people to use v7.

**Pull request merged**
