### PR TITLE
feat: add ability to parse crypto metadata

### PR DESCRIPTION
**Pull request by fredwes**
Implement parsing for crypto metadata. These changes will allow for parsing of Always Encrypted metadata as part of the column metadata parser, if the Always Encrypted feature is enabled on the connection.

This is another PR of the effort to break down the large Always Encrypted PR into smaller, more manageable ones for review. #1020

### CODE REVIEW

**Comment by IanChokS** [comment]
@fredwes I wonder if it's good to start these PR titles with `AE` or `Always Encrypted` so it's easier to see in the list of PR's

**Comment by fredwes** [comment]
@IanChokS Good idea, will do!

**Comment by IanChokS** [comment]
Also, I think the old commit messages shouldn't start with `feat` because that will trigger a tedious release right away 😅

**Comment by fredwes** [comment]
@IanChokS I rebased and updated the commit message type to chore.

**Comment by fredwes** [comment]
Closing this PR, will re-open with updated commit message

**Pull request closed without merging**
